version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: michn
      POSTGRES_PASSWORD: waffles
      POSTGRES_DB: sensordata
    ports:
      - "5432:5432"
    networks:
      - homesrv

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: neal.mike88@gmail.com
      PGADMIN_DEFAULT_PASSWORD: waffles
    ports:
      - "5050:80"
    networks:
      - homesrv
  
  mosquitto:
    container_name: mosquitto-mqtt
    image: eclipse-mosquitto:latest
    volumes:
      - ./config:/mosquitto/config/
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - '1883:1883'
      - '8883:8883'
    networks:
      - homesrv
    restart: always

networks:
  homesrv:

volumes:
  mosquitto_data:
  mosquitto_log:
